name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      with:
        arguments: build jacocoTestReport
        build-root-directory: triangle
    - name: Upload JaCoCo coverage report as a workflow artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: jacoco-report
        path: triangle/lib/build/reports/jacoco/test/html/
    - name: Upload library JAR
      uses: actions/upload-artifact@v3.1.1
      with:
        name: lib.jar
        path: triangle/lib/build/libs/lib.jar
